-- Create route_price table
CREATE TABLE IF NOT EXISTS route_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "from" TEXT NOT NULL,
    "to" TEXT NOT NULL,
    price NUMERIC NOT NULL,
    price_vito NUMERIC,
    price_maybach NUMERIC,
    price_minibus NUMERIC,
    currency TEXT DEFAULT 'EUR'
);

-- Create extra_services table
CREATE TABLE IF NOT EXISTS extra_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    image TEXT,
    price NUMERIC NOT NULL,
    currency TEXT DEFAULT 'EUR',
    is_active BOOLEAN DEFAULT true
);

-- Create gallery table
CREATE TABLE IF NOT EXISTS gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    type TEXT DEFAULT 'image'
);

-- Create settings table
CREATE TABLE IF NOT EXISTS settings (
    id BIGINT PRIMARY KEY,
    phone TEXT,
    email TEXT
);

-- Insert default settings
INSERT INTO settings (id, phone, email) 
VALUES (1, '05000000000', 'info@viptransferantalyataksi.com')
ON CONFLICT (id) DO NOTHING;
